# Generated by Django 3.2 on 2022-09-08 19:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Valor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('precio_de_venta', models.DecimalField(decimal_places=2, max_digits=6)),
                ('costo_de_adquisicion', models.DecimalField(decimal_places=2, max_digits=6)),
            ],
        ),
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_producto', models.CharField(max_length=50, verbose_name='producto')),
                ('tipo_de_prenda', models.CharField(max_length=50, verbose_name='prenda')),
                ('color', models.CharField(choices=[('ROJO', 'Rojo'), ('AZUL', 'Azul'), ('VERDE', 'Verde'), ('AMARILLO', 'Amarillo'), ('MOSTAZA', 'Mostaza'), ('BORDO', 'Bordo')], max_length=35, verbose_name='color')),
                ('talle', models.CharField(choices=[('XS', 'XS'), ('S', 'S'), ('M', 'M'), ('L', 'L'), ('XL', 'XL'), ('XXL', 'XXL')], max_length=5, verbose_name='talle')),
                ('valor', models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='productos.valor')),
            ],
        ),
    ]
