# Generated by Django 4.1.2 on 2022-10-31 17:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productos', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='producto',
            name='color',
            field=models.CharField(choices=[('ROJO', 'Rojo'), ('AZUL', 'Azul'), ('VERDE', 'Verde'), ('AMARILLO', 'Amarillo'), ('MOSTAZA', 'Mostaza'), ('BORDO', 'Bordo'), ('NEGRO', 'Negro'), ('BLANCO', 'Blanco')], max_length=35, verbose_name='color'),
        ),
        migrations.AlterField(
            model_name='producto',
            name='nombre_producto',
            field=models.CharField(max_length=50),
        ),
    ]
