# Generated by Django 3.2 on 2022-09-08 19:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productos', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='producto',
            name='tipo_de_prenda',
            field=models.CharField(choices=[('REMERA', 'Remera'), ('BUZO', 'Buzo'), ('CAMPERA', 'Campera'), ('PANTALON', 'Pantalon'), ('BERMUDAS', 'Bermudas'), ('ACCESORIOS', 'Accesorios')], max_length=50, verbose_name='prenda'),
        ),
    ]
