# Generated by Django 4.1.1 on 2022-11-08 23:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productos', '0002_alter_producto_color_alter_producto_nombre_producto'),
    ]

    operations = [
        migrations.AlterField(
            model_name='producto',
            name='fecha_agregado',
            field=models.DateTimeField(auto_now_add=True, verbose_name='date'),
        ),
    ]
